#!/bin/bash
#
# Daemon Name: raumsrvDaemon
#  
# chkconfig: - 58 74
# description: Raumserver Daemon start/stop/restart script


NAME="raumsrvDaemon"
DAEMON="/usr/development/raumfeld/git/Raumserver/source/RaumserverDaemon/$NAME"

start() { 
  
    # TODO: wait until network is ready
    #[ "$NETWORKING" = "no" ] && exit 1

    # Check if executable binary is there
    [ -x /usr/development/raumfeld/git/Raumserver/source/RaumserverDaemon/$prog ] || exit 5
 
    # Check if the daemon is already running. If so write an info to the console and do nothing
    if [ "$(pidof $NAME)" ] 
    then
        printf $"Raumserver Daemon is already running!\n"
	RETVAL=-1
    else     
        # Start the raumserver daemon
        printf $"Starting $prog: \n"
        $DAEMON
        RETVAL=$?
        printf $"\n"
    fi     

    return $RETVAL
}

stop() {
    printf $"Shutting down $NAME: "
    pkill $NAME
    RETVAL=$?
    printf "$RETVAL \n"

    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status $prog
        ;;
  restart)
        stop
        start
        ;;
   *)
        printf $"Usage: $0 {start|stop|status|restart}\n"
        exit 2
esac
